### ISSUE TITLE
barbarian goes too late to t2

### ISSUE THREAD

**Issue by fruehling76** [beyond-all-reason/BARbarIAn#1]
some feedback based on yesterdays games:

AI too late on t2
ai does very good on t1 but suck from the moment it has to go t2. there it gets surpassed by human. only 2 of 5 ai werer going to t2 in a 40min match on delta siege dry. first one around min 23 when human tries to go around min 10-12 there. they already had all over 20 metal income and lots of metal in storage.

solution:

- lower the trigger for t2 or spread it wider (on the lower end)
- the absolut top would be when it starts a lets say teching phase were it reclaim old lab for getting additioal metal in case it is missing some.

i wonder also if it is possible in multiplayer games to let ai play sometimes with kind of teching ai-player, which maybe reclaim com to level up very early and then force economy and build t2 cons for other players which they use them too build some t2 mexes before they level up. comleting that task it should force economy again before going early to t3

**Comment by rlcevg** [comment]
Required new feedback for 0.5 version. Though it probably won't differ much.
Large team games (more than 4 players on one side) are usually a bit different than small or 1v1. Probably players even select dedicated roles, like a nuke rusher that rushes nuke after 2nd minute in game. Economy is different (less mexes per player). Those things affect AI experience that was developed with 1v1 up-to 3v3 in mind.

I don't trust time marks for AI phases (though BARb has it and it's a flaw). When faction switch should happen?
1) enough metal and energy income (how fast to buid t2 fac, how fast t2 fac builds units)
2) an army (with defences) more powerful than enemy's
And this is from 1v1 perspective only.

Currently the switch event is about frame mark or metal income: with current config it builds 3 caretakers per factory before switch; fac's metal usage is set to 10 in config, and caretaker's too. BARb will switch when it reaches random(10,15)`th minute or more than 10+(10*3) metal income, and if it has safe area to build.

Can someone describe exactly switch-rules (for any teams, without frame marks)?

No building and reclaiming lower-tech units after teching up requires new set of economy rules; planned for the future, but nothing particular in mind at this very moment.

**Comment by fruehling76** [comment]
general factors for switch rules for mp could be:

- metal production paired with an certain amount of energy productions
- metal in storage
- opponent has t2
- time frame
- more powerful army

for every single ai player i would generate at game start personal values within a certain range for each of the rules. ai changes then when 2/3 (that value can also be randomized) of 5 rules are positiv. so we have some ai staying longer on t1 others try to upgrade fast.

then there should also some modifier for the rules based on number of players and ressources the map has to offer. for example if map has not much metal/player to offer the time frame should be higher while the necessary metal production could be decreased a bit.




ps: whats a caretaker btw?

**Comment by fruehling76** [comment]
as well in bigger games we could randomly spawn a tech ai within a chance of lets say 30%. which basically starts in the very back, build some basic stuff (kind of 2 constructors, 1 nano,  2llts, 10 metal income 300 energy income)and then tries to tech immediately. maybe with self d com and reclaiming 90% of its metal (later it can be resurrected again). com must be blocked to other ai as well

**Comment by rlcevg** [comment]
caretaker = Nano Turret / armnanotc / cornanotc

**Comment by fruehling76** [comment]
what do u think about the concept of different switch rules like example above and to start the upgrade when 2 or 3 of them are positive? and how do u define a "save area"

**Comment by fruehling76** [comment]
values for siwtchrules in mp:
- metal production range from 20-30, e should be at least 200-300
- metal in storage: ca 1400 (which is approximately the half that u need to build a t2 lab
- time from should range from 8min to 25min. there is should be generous cause ressources should have a bigger role. time should just be an additional trigger that forces upgrade at a certain point.

**Comment by rlcevg** [comment]
JFYI: only brainstorming right now and collecting data, as in the near future i won't have time to code it.

All conditions except time frame seems sane to me in skirmish battle (not mission).
Metal storage can be coupled with metal income condition: the more in storage - the less income AI needs to switch.
Safe area - if you mean map control then it can be a percent of taken mex spots (divided by enemy count for FFA), maybe covered by defences.

About metal production range: 20-30 is ok, but also lets go further to answer why 20-30. AI can calculate how fast it can build t2 factory (or t3, etc.) with its current income. If it has enough income to build new-tech factory in 2 minutes (or 40 seconds?) then AI should go for it.
Maybe available mobile buildpower also should be considered, but currently AI makes new builders according to income, so lack of it shouldn't be a problem, unless enemy suddenly destroyed a big chunk of it (hmm).
Also AI should check average time to build units from new factory (how fast t2 fac should produce units and why that fast?).

And maybe those 2 minutes (or 40 seconds?) can be a derivative of how safe AI is or how stronger than the enemy it is. AI can pretend that opponent has same level of income, and so the time needed to catch up for the enemy with AI's power (in mobile attackers and static defences) is the time window to switch tech. Of course enemy's army power is calculated only with units that were in LOS, so it won't be accurate.

* opponent has t2 - good point, it is probably mandatory trigger, as t2 > t1 and AI will lose without tech-ing. Actually if power of t2 unit is less then total power of t1 units that has total cost equal or less than t2 unit then t2 < t1. But lets take t2 > t1 and t3 > t2 as granted.

**Comment by fruehling76** [comment]
about metal production range. 20-30 metal is my own experience - the point were i usuall try to level up depends always a on actual situation like:
- am i underpressure? 
- has enemy already t2, 
- do i have time and resssources?
- what to expect from opponent then next 2-3 min? 
- can i make maybe a lethal hit by staying on t1 and produce a hell of units instead

AND ... also i take time into consideration. if i am playing on comet catcher for example and i see its 9/10min i start to consider when is the right moment to go t2. if i sometimes reach min 15 i have the feeling i really should force t2 now.

sometimes there is the opportunity to reclaim a big metal field. that also triggers me often to use that ressources to go fast t2. 

if i decide, "now i go t2" i often shut down other other projects to reduce metal and e expense, make sure that i have plents of energy and also constructors/nanos available, wait some seconds until metal storage fills up a bit, reclaim often t1 and then i go full power to make a fast transition in about less than 1 min. 

the point is if u wait a bit until storage fill up to around 1500 metal u always have the possibility to change your mind and adapt action to new situations (like an attack). important is to have enough buildpower available.
