### ISSUE TITLE
A crash log

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/BARbarIAn#14]
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\AI\Skirmish\BARb\stable\SkirmishAI.dll 0x000628FD /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/stl_vector.h:95
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\AI\Skirmish\BARb\stable\SkirmishAI.dll 0x00003AC4 /home/runner/work/spring/spring/spring/AI/Skirmish/BARb/src/circuit/CircuitAI.cpp:772
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\AI\Skirmish\BARb\stable\SkirmishAI.dll 0x0000B8E0 /home/runner/work/spring/spring/spring/AI/Skirmish/BARb/src/circuit/map/InfluenceMap.cpp:350
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\AI\Skirmish\BARb\stable\SkirmishAI.dll 0x000014EA /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/basic_string.h:237
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x0091132B rts/ExternalAI/SkirmishAIHandler.h:172
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x00914D9C rts/ExternalAI/SkirmishAIWrapper.cpp:468
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x008EF346 rts/ExternalAI/EngineOutHandler.cpp:578
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x005350D5 /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/shared_ptr_base.h:729
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x00433965 /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/atomic_base.h:419
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x00862FAC rts/System/SpringApp.cpp:767
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x008660E0 rts/System/SpringApp.cpp:806
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x0084FBEC rts/System/Main.cpp:48
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x00F89F29 rts/System/Main.cpp:100
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x004013B4 x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:341
D:\Games\Beyond-All-Reason\data\engine\105.1.1-653-g954b191 bar\spring.exe 0x004014DB x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:197
C:\WINDOWS\SYSTEM32\ntdll.dll 0x00052651 ??:0

**Comment by rlcevg** [comment]
somehow translate is incorrect.
manual translation:
```
(gdb) info line *0x6B1E28FD
Line 50 of "/home/runner/work/spring/spring/spring/AI/Skirmish/BARb/src/circuit/scheduler/Scheduler.cpp"
   starts at address 0x6b1e28fd <_ZN7circuit10CScheduler14ProcessReleaseEv+141> and ends at 0x6b1e290b <_ZN7circuit10CScheduler14ProcessReleaseEv+155>.
(gdb) info line *0x6b183ac4
Line 182 of "/usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/move.h" starts at address 0x6b183ac4 <_ZN7circuit10CCircuitAI7ReleaseEi+372>
   and ends at 0x6b183acb <_ZN7circuit10CCircuitAI7ReleaseEi+379>.
(gdb) info line *0x6b18b8e0
Line 217 of "/home/runner/work/spring/spring/spring/AI/Skirmish/BARb/src/circuit/CircuitAI.cpp"
   starts at address 0x6b18b8e0 <_ZN7circuit10CCircuitAI15HandleGameEventEiPKv+2192>
   and ends at 0x6b18b8e8 <_ZN7circuit10CCircuitAI15HandleGameEventEiPKv+2200>.
(gdb) info line *0x6b1814ea
Line 75 of "/home/runner/work/spring/spring/spring/AI/Skirmish/BARb/src/AIExport.cpp" starts at address 0x6b1814ea <handleEvent(int, int, void const*)+154>
   and ends at 0x6b1814eb <handleEvent(int, int, void const*)+155>.
```

**Comment by rlcevg** [comment]
Was unable to reproduce.
Fix: https://github.com/rlcevg/CircuitAI/commit/ee976f86ea00cfb8a784d0d7f8f9edd9b44622f9
