### ISSUE TITLE
Crash logs for Engine 902

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/BARbarIAn#20]
I have collected a few crash logs that all indicate skirmishai as the crash source, if you have some time, would you mind looking into them, @rlcevg ?
[infolog_2561.log](https://github.com/beyond-all-reason/BARbarIAn/files/8528961/infolog_2561.log)
[infolog_2562.log](https://github.com/beyond-all-reason/BARbarIAn/files/8528963/infolog_2562.log)
[infolog_2568.log](https://github.com/beyond-all-reason/BARbarIAn/files/8528964/infolog_2568.log)
[infolog_2545.log](https://github.com/beyond-all-reason/BARbarIAn/files/8528965/infolog_2545.log)
[infolog_2558.log](https://github.com/beyond-all-reason/BARbarIAn/files/8528966/infolog_2558.log)

**Comment by rlcevg** [comment]
Thanks. Missed some `unsigned i = -1; if (i < 0) {...}`. Have to do something to amount of warnings 3rd-party libs produce during compilation...

**Comment by rlcevg** [comment]
fixed in https://github.com/beyond-all-reason/spring/pull/248
